### PR TITLE
Fixed issue #1

### PR DESCRIPTION
**Pull request by wcomnisky**
- Increased the source and target compatibility to 1.8;
- Upgraded the plugins: coveralls, coveralls and testng;
- Upgraded the Gradle version to 2.10;

### CODE REVIEW

**Comment by mkuthan** [comment]
Thank a lot for the PR. Could you also bump jdk level in .travis.yml configuration file, please?

**Comment by wcomnisky** [comment]
Should we keep backward compatibility with 1.7?

**Comment by mkuthan** [comment]
Forget about 1.7, go ahead with 1.8 :-)

**Comment by wcomnisky** [comment]
Indeed! Java 7 reached the end of its support lifecycle on April 2015.

**Pull request merged**
